version: '3.8'

name: moodle-prod

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: moodlepass
    volumes:
      - moodle-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moodleuser"]
      interval: 30s
      timeout: 10s
      retries: 5

  moodle:
    image: bitnami/moodle:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepass
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin123
      MOODLE_EMAIL: admin@irtuniv.dz
      MOODLE_URL: https://your-domain.com  # Change this to your real domain
      PHP_FPM_ENABLE: yes  # Prevent Apache hangs
    volumes:
      - moodle-app:/bitnami/moodle
      - moodle-data:/bitnami/moodledata
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login/index.php || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  moodle-db-data:
  moodle-app:
  moodle-data:
